name: Trusted CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Print secret length
          run: echo "Length of TEST_SECRET is ${#TEST_SECRET}"
          env:
            TEST_SECRET: ${{ secrets.TEST_SECRET }}